#install:
#  - pip3 install -r requirements.txt
#script:
#    - if [ $TRAVIS_OS_NAME == "linux" ];   then pyinstaller -F beatcounter.py -n beatcounter.appimage ; fi
#    - if [ $TRAVIS_OS_NAME == "windows" ]; then pyinstaller -F beatcounter.py -n beatcounter.exe      ; fi
#    - if [ $TRAVIS_OS_NAME == "osx" ];     then pyinstaller -F beatcounter.py -n beatcounter.dmg      ; fi
deploy:
  provider: releases
  api_key: "9a58fbbb3ea16ac25bfee55aef80ec719e0477df"
  file: "testfile"
  skip_cleanup: true
  draft: true
