language: python
install:
- pip3 install -r requirements.txt
script:
- if [ $TRAVIS_OS_NAME == "linux" ];   then pyinstaller -F test.py -n test.appimage
  ; fi
- find dist
deploy:
  provider: releases
  api_key: 
    secure: InN9eTB7RuEwObD8CZBsZuuI318d3XuoIa30ZZcjGH4fEboiubYv1jD+yDWqIkykbbGVvNI1rX2KkMGQLYGi7qlkIm6z5Btw1Rb/qC+ceOgaQE+OY3aF3lCZBTUdWP7YOklcn2xHLJuoSRcVlfcmvlLWZLzC2F01foYnpP6G382ZXgeV0LUclCqKihJyoVCH2IWGRx1tJMKNv9Ah8huaTFkNu3AQ052l/HQ1ZL7srRf/W+54gZuNF7NKmO5ICCaAWAn+r+AGdd/4cgIA7NJMb82mvfI2NSzY0u+GPe4rWIesHaWoBWQKoKg3orTvFL7qRFU8dbiccV4rQnhl6YJx/TnNMaNi0DYS3CAbTdn1pGZyMDAQhiqpUWR7NslTWEQkLKdw1TPTq597DDotH6VeiccEidgs7cQCZVOhZxZQsjZErPG746ZdRwxlldbH9ZMTJuHzGO7PMB5xAVaEdKOV4A8w7K31GxVULnjSlMajgLFzfVzWf4uFaahor0zQw/fqU1zTazFTx7f3h4rBCY2yjX2FNeqhr56wrLdl7t/SCuyYLP/P+l3EwZGyhQPjpGQYH+nWo1UeDG62yksK/lZs1w3DrqdCbTeABIU9vQl9ekM6ewD9K/ZXlpAZQCozxuyvKmud8DqHIP8x+Ph7DxPNgErc1u0oqkKhRluTQtDJAlI=
  file: dist/test.appimage
  overwrite: true
  skip_cleanup: true
