language: python
install:
  - pip3 install -r requirements.txt
script:
    - if [ $TRAVIS_OS_NAME == "linux" ];   then pyinstaller -F test.py -n test.appimage ; fi
#    - if [ $TRAVIS_OS_NAME == "windows" ]; then pyinstaller -F beatcounter.py -n beatcounter.exe      ; fi
#    - if [ $TRAVIS_OS_NAME == "osx" ];     then pyinstaller -F beatcounter.py -n beatcounter.dmg      ; fi
    - find dist
deploy:
  provider: releases
  api_key: "e50bd8bcf44ca091cc534870e9dc6978ea11291e"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
